### PR TITLE
507 inclusive gateway condition

### LINKED ISSUE #507: I cannot set condition on a sequence flow outgoing from inclusive gateway
__Describe the Bug__

I cannot set condition on a sequence flow outgoing from inclusive gateway. Condition group is missing.

Before:

image

Now:

image

__Steps to Reproduce__

1. Create an inclusive gateway
2. Append a task and select the sequence flow
3. now this happens

__Expected Behavior__

I can set condition.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

### PR DESCRIPTION
**Pull request by MaxTru**
closes #507

### CODE REVIEW

**Comment by MaxTru** [comment]
@smbea @marstamm could you please have a look? This is just a small little fix. Thanks!

**Comment by marstamm** [comment]
> For exlusiveGateways we have conditions

Sorry, I was not clear. I meant for Inclusive/Complex gateways

**Comment by marstamm** [comment]
Thanks for confirming that we want to replicate it 1:1 :rocket:

**Review by marstamm — APPROVED** [review]

**Comment by MaxTru** [comment]
Thanks for the quick review / follow-up!

**Pull request merged**
