### PR TITLE
Improve tooltips

### PR DESCRIPTION
**Pull request by smbea**
Related to https://github.com/camunda/camunda-modeler/issues/3611

### CODE REVIEW

**Comment by smbea** [comment]
@christian-konrad could you have a look at this? Please review the content and let me know if anything is missing too. You can test them out in the modeler:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/tooltips/camunda-modeler-tooltips-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/tooltips/camunda-modeler-tooltips-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/tooltips/camunda-modeler-tooltips-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/tooltips/camunda-modeler-tooltips-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/tooltips/camunda-modeler-tooltips-win-x64.zip

**Comment by smbea** [comment]
I will pick this up after my FTO since it isn't urgent. Also feel free to take over and merge, if you see fit.

**Review by christian-konrad — APPROVED** [review]
Looks good! I updated some tooltips to remove ambiguity and to update them (some docs where this was taken from are outdated)

**Comment by philippfromme** [comment]
@christian-konrad Fixed the merge conflict. Can be reviewed now.

**Pull request merged**
