### PR TITLE
feat(feel-popup): provide container for feel popup editors

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Use via

```js
propertiesPanel: {
  feelPopupContainer: ...
}
```

Follow up of https://github.com/bpmn-io/properties-panel/pull/280

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
I'd like to open this up but `npm` does not allow me to update the package-lock currently 🤡 I will do once the outages are gone.

@bpmn-io/modeling-dev will we need to adapt this in camunda-bpmn-js as well to make the feature work?

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
Please add a note to the changelog.

**Comment by nikku** [comment]
> will we need to adapt this in camunda-bpmn-js as well to make the feature work?

camunda-bpmn-js only passes through properties, so I'd say no.

**Comment by pinussilvestrus** [comment]
> Please add a note to the changelog.

Thanks for mentioning 👍 done via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/970/commits/9dc593c03f82ecefbc1f6f97651b19fca32d4f76

**Review by nikku — APPROVED** [review]

**Pull request merged**
