### PR TITLE
Element Templates Feature Is Aware of Versions

### LINKED ISSUE #398: Element Templates Feature Is Aware of Versions
* [x] element templates are considered unique based on ID plus version (two element templates can have same ID but different version making them unique)
* [x] validation is aware of versions
* [x] show version instead of date in element template description
* [x] element template select is aware of versions
* [x] versions are applied when applying an element template (`camunda:modelerTemplateVersion`)

> Note: This issue is not about handling the case of applying a new version of an element template. See https://github.com/bpmn-io/bpmn-js-properties-panel/issues/399.

Related to https://github.com/camunda/camunda-modeler/issues/1969
Child of https://github.com/camunda/camunda-modeler/issues/1969

### PR DESCRIPTION
**Pull request by philippfromme**
* element templates are considered unique based on ID plus version (two element templates can have same ID but different version making them unique)
* validation is aware of versions
* show version instead of date in element template description
* element template select is aware of versions
* versions are applied when applying an element template (`camunda:modelerTemplateVersion`)
* simplify element template select (can only be visible if no element template applied)

> Note: This PR is not about handling the case of applying a new version of an element template. See https://github.com/bpmn-io/bpmn-js-properties-panel/issues/399.

__Which issue does this PR address?__

Related to https://github.com/camunda/camunda-modeler/issues/1969
Closes #398

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by barmac** [comment]
image

It blows up when the dropdown is opened and I click on the canvas.

**Comment by barmac** [comment]
I wasn't able to reproduce it on 4.4.0.

Recording + log:

recording

<details><summary>Error log</summary>
```
[/Users/maciej/workspace/bpmn-io/zeebe-modeler/resources/diagram/simple.bpmn] Failed to execute 'querySelector' on 'Element': '[data-entry=""><img height=100 width=100 src='data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA5NjAg%0D%0AOTYwIj48cGF0aCBmaWxsPSIjZmZmIiBkPSJNOTYwIDYwdjgzOWMwIDMzLTI3IDYxLTYwIDYxSDYw%0D%0AYy0zMyAwLTYwLTI3LTYwLTYwVjYwQzAgMjcgMjcgMCA2MCAwaDgzOWMzNCAwIDYxIDI3IDYxIDYw%0D%0AeiIvPjxwYXRoIGZpbGw9IiM1MmI0MTUiIGQ9Ik0yMTcgNTQ4YTIwNSAyMDUgMCAwIDAtMTQ0IDU4%0D%0AIDIwMiAyMDIgMCAwIDAtNCAyODYgMjAyIDIwMiAwIDAgMCAyODUgMyAyMDAgMjAwIDAgMCAwIDQ4%0D%0ALTIxOSAyMDMgMjAzIDAgMCAwLTE4NS0xMjh6TTc1MiA2YTIwNiAyMDYgMCAwIDAtMTkyIDI4NSAy%0D%0AMDYgMjA2IDAgMCAwIDI2OSAxMTEgMjA3IDIwNyAwIDAgMCAxMTEtMjYwQTIwNCAyMDQgMCAwIDAg%0D%0ANzUyIDZ6TTYyIDBBNjIgNjIgMCAwIDAgMCA2MnYzOThsNjAgNDZhMjU5IDI1OSAwIDAgMSA4OS0z%0D%0ANmM1LTI4IDEwLTU3IDE0LTg1bDk5IDIgMTIgODVhMjQ2IDI0NiAwIDAgMSA4OCAzOGw3MC01MiA2%0D%0AOSA3MS01MiA2OGMxNyAzMCAyOSA1OCAzNSA5MGw4NiAxNC0yIDEwMC04NiAxMmEyNDAgMjQwIDAg%0D%0AMCAxLTM4IDg5bDQzIDU4aDQxM2MzNyAwIDYwLTI3IDYwLTYxVjQwN2EyMjAgMjIwIDAgMCAxLTQ0%0D%0AIDQwbDIxIDg1LTkzIDM5LTQ1LTc2YTI1OCAyNTggMCAwIDEtOTggMWwtNDUgNzYtOTQtMzkgMjIt%0D%0AODVhMjk4IDI5OCAwIDAgMS03MC02OWwtODYgMjItMzgtOTQgNzYtNDVhMjU4IDI1OCAwIDAgMS0x%0D%0ALTk4bC03Ni00NSA0MC05NCA4NSAyMmEyNzEgMjcxIDAgMCAxIDQxLTQ3eiIvPjwvc3ZnPg=='>-collapsible"]' is not a valid selector.
    at query (webpack-internal:///../../bpmn-js-properties-panel/node_modules/min-dom/dist/index.esm.js:513:13)
    at eval (webpack-internal:///../../bpmn-js-properties-panel/lib/PropertiesPanel.js:933:25)
    at arrayEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/forEach.js:38:10)
    at eval (webpack-internal:///../../bpmn-js-properties-panel/lib/PropertiesPanel.js:932:7)
    at arrayEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/forEach.js:38:10)
    at eval (webpack-internal:///../../bpmn-js-properties-panel/lib/PropertiesPanel.js:929:5)
    at arrayEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/forEach.js:38:10) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]
[/Users/maciej/workspace/bpmn-io/zeebe-modeler/resources/diagram/simple.bpmn] Failed to execute 'querySelector' on 'Element': '[data-entry=""><img height=100 width=100 src='data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA5NjAg%0D%0AOTYwIj48cGF0aCBmaWxsPSIjZmZmIiBkPSJNOTYwIDYwdjgzOWMwIDMzLTI3IDYxLTYwIDYxSDYw%0D%0AYy0zMyAwLTYwLTI3LTYwLTYwVjYwQzAgMjcgMjcgMCA2MCAwaDgzOWMzNCAwIDYxIDI3IDYxIDYw%0D%0AeiIvPjxwYXRoIGZpbGw9IiM1MmI0MTUiIGQ9Ik0yMTcgNTQ4YTIwNSAyMDUgMCAwIDAtMTQ0IDU4%0D%0AIDIwMiAyMDIgMCAwIDAtNCAyODYgMjAyIDIwMiAwIDAgMCAyODUgMyAyMDAgMjAwIDAgMCAwIDQ4%0D%0ALTIxOSAyMDMgMjAzIDAgMCAwLTE4NS0xMjh6TTc1MiA2YTIwNiAyMDYgMCAwIDAtMTkyIDI4NSAy%0D%0AMDYgMjA2IDAgMCAwIDI2OSAxMTEgMjA3IDIwNyAwIDAgMCAxMTEtMjYwQTIwNCAyMDQgMCAwIDAg%0D%0ANzUyIDZ6TTYyIDBBNjIgNjIgMCAwIDAgMCA2MnYzOThsNjAgNDZhMjU5IDI1OSAwIDAgMSA4OS0z%0D%0ANmM1LTI4IDEwLTU3IDE0LTg1bDk5IDIgMTIgODVhMjQ2IDI0NiAwIDAgMSA4OCAzOGw3MC01MiA2%0D%0AOSA3MS01MiA2OGMxNyAzMCAyOSA1OCAzNSA5MGw4NiAxNC0yIDEwMC04NiAxMmEyNDAgMjQwIDAg%0D%0AMCAxLTM4IDg5bDQzIDU4aDQxM2MzNyAwIDYwLTI3IDYwLTYxVjQwN2EyMjAgMjIwIDAgMCAxLTQ0%0D%0AIDQwbDIxIDg1LTkzIDM5LTQ1LTc2YTI1OCAyNTggMCAwIDEtOTggMWwtNDUgNzYtOTQtMzkgMjIt%0D%0AODVhMjk4IDI5OCAwIDAgMS03MC02OWwtODYgMjItMzgtOTQgNzYtNDVhMjU4IDI1OCAwIDAgMS0x%0D%0ALTk4bC03Ni00NSA0MC05NCA4NSAyMmEyNzEgMjcxIDAgMCAxIDQxLTQ3eiIvPjwvc3ZnPg=='>-collapsible"]' is not a valid selector.
    at query (webpack-internal:///../../bpmn-js-properties-panel/node_modules/min-dom/dist/index.esm.js:513:13)
    at eval (webpack-internal:///../../bpmn-js-properties-panel/lib/PropertiesPanel.js:933:25)
    at arrayEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/forEach.js:38:10)
    at eval (webpack-internal:///../../bpmn-js-properties-panel/lib/PropertiesPanel.js:932:7)
    at arrayEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/forEach.js:38:10)
    at eval (webpack-internal:///../../bpmn-js-properties-panel/lib/PropertiesPanel.js:929:5)
    at arrayEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (webpack-internal:///../../bpmn-js-properties-panel/node_modules/lodash/forEach.js:38:10) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]
```
</details>

**Comment by philippfromme** [comment]
@barmac This is an issue unrelated to this PR. The XSS template breaks a CSS selector when updating the properties panel. I was able to reproduce this using Camunda Modeler v4.4.0. I guess this has been broken for a long time because we don't escape IDs that are used for CSS selectors.

image

**Comment by barmac** [comment]
Thank you Philipp. Now I know why I wasn't able to reproduce that with 4.4.0. I used another template but not XSS task. Sorry for unnecessary alert.

**Review by barmac — APPROVED** [review]
I added https://github.com/bpmn-io/bpmn-js-properties-panel/pull/400/commits/0a94507b40ac92ccddc18abe1dbcd02584e166b8 and rebased on `master`. Let's merge that.

**Comment by philippfromme** [comment]
❤️

**Pull request merged**
