### PR TITLE
Add `zeebe:Properties` Support

### PR DESCRIPTION
**Pull request by philippfromme**
# Changes

* add zeebe:Property support for all flow elements
* add zeebe:Property support for element templates

brave_gXLuVx6yb8

---

Closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/731

### CODE REVIEW

**Review by nikku — COMMENTED** [review]
Do we test `optional` binding, i.e. entry only being created _if_ non-empty?

**Comment by philippfromme** [comment]
> Do we test `optional` binding, i.e. entry only being created _if_ non-empty?

I added the missing tests. CI should be green in a minute.

**Comment by nikku** [comment]
Thanks. Also coverage is happy now! :)

**Comment by nikku** [comment]
Where exactly did you add the tests :eyes:

**Review by nikku — CHANGES_REQUESTED** [review]
Optional does not work as expected.

In fact I could reproduce using output logging (https://github.com/bpmn-io/bpmn-js-properties-panel/pull/747) that an empty optional property `npm run start:cloud-templates` is still serialized.

**Comment by philippfromme** [comment]
> Optional does not work as expected.
> 
> In fact I could reproduce using output logging (#747) that an empty optional property `npm run start:cloud-templates` is still serialized.

I'll look into that.

**Comment by philippfromme** [comment]
@nikku I'm not sure what you mean. Do you mean that a property with `"optional": true` shouldn't end up in the XML unless there is value? I mistook that for not required. 😅 

image

**Comment by nikku** [comment]
@philippfromme Exactly. Empty fields (according to our optional behavior) shall not be serialized.

**Comment by nikku** [comment]
Verified optional entry change via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/745/commits/0d75f186334eb1caad7a4df979a8788096f75e1f.

Looks good to me.

**Review by nikku — APPROVED** [review]

**Pull request merged**
