### PR TITLE
chore: prepare 1.24.0

### PR DESCRIPTION
**Pull request by marstamm**

### CODE REVIEW

**Comment by barmac** [comment]
Shall we also include the fixes I prepared?

**Comment by marstamm** [comment]
Added the changes via [fc33fa6](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/924/commits/fc33fa65d2de90b0f53ee5144ff8c0c8731cbf84)

**Comment by barmac** [comment]
+ https://github.com/bpmn-io/bpmn-js-properties-panel/pull/925

**Comment by marstamm** [comment]
Sorry, just saw that there are other open PRs. I'll review those as well

**Comment by marstamm** [comment]
Rebased and added the latest fixes

**Review by barmac — APPROVED** [review]

**Pull request merged**
