### PR TITLE
Translate Error Messages

### LINKED ISSUE #300: Error Messages Not Translated
image
In Utils.js and maybe some easily overlooked places,no translate module or forget to translate the description.

### PR DESCRIPTION
**Pull request by 919980059**
This PR enables translating error messages returned by [IdProps#isIdValid](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/Utils.js#L146) and [IdProps#validateId](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/Utils.js#L161).

Closes #300.

### CODE REVIEW

**Comment by philippfromme** [comment]
Thanks for contributing. The CI is still failing, could you fix the test cases that are now failing?

**Comment by 919980059** [comment]
Sorry i forgot to run test , i'll fix it later.

**Comment by 919980059** [comment]
> Thanks for contributing. The CI is still failing, could you fix the test cases that are now failing?

Sorry i forgot to run test , i'll fix it later.

**Comment by philippfromme** [comment]
I've made a few adjustments. Thanks for your contribution.

Closed via https://github.com/bpmn-io/bpmn-js-properties-panel/commit/43c12d70c685d7917b7d77ce724f5de9f5be3892.

**Pull request closed without merging**
