### PR TITLE
chore: rearrange process props by relevance

### PR DESCRIPTION
**Pull request by Skaiir**
Related to https://github.com/camunda/camunda-modeler/issues/2680

### CODE REVIEW

**Comment by barmac** [comment]
OK so as we anticipated this moves not only process props, e.g. 
image

**Comment by MaxTru** [comment]
@Skaiir , let's align with @andreasgeier and Ingo please to ensure we understand whether we want to change order GLOBALLY or ONLY FOR process

**Comment by barmac** [comment]
External task is also moved: 
image

**Comment by ingorichtsmeier** [comment]
Hi @barmac, 

for the timer intermediate event, your left screenshot looks as in my 5.0.0-alpha1 and it's better than the right one, as it brings the Priority under Job execution closer to the timer definition. 

Sidenote: Async continuation didn't make sense for intermediate timers as the timer are implemented as jobs. This section could be lower here, but I think only here and not for service tasks. But this is acceptable.

**Comment by ingorichtsmeier** [comment]
For the external service task, your left side look different then the Modeler 5.0.0-alpha1, but also better. As the External Task appears only for Implementation type External, it should be as close as possible to Implementation.

**Comment by Skaiir** [comment]
@ingorichtsmeier As close as possible but still below candidate starter, right?

**Comment by ingorichtsmeier** [comment]
Yes. On the process tab, it is less important than the candidate starter.

**Comment by Skaiir** [comment]
@barmac This should be a lot better.

**Review by barmac — APPROVED** [review]
I like it.

**Pull request merged**
