### PR TITLE
Support (optional) tooltip for drop down options

### PR DESCRIPTION
**Pull request by rajgoel**
### Proposed Changes

* This is a small extra feature allowing to provide a [title attribute](https://www.w3schools.com/tags/att_title.asp) for adding tooltips to dropdown menu options

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Thanks for your contribution @rajgoel. One thing you could do before merging this PR

* Squash + Update your commit to [fit our guideline](https://github.com/bpmn-io/bpmn-js/blob/develop/.github/CONTRIBUTING.md#creating-a-pull-request)

**Comment by rajgoel** [comment]
So, I figured out how to squash the commits. Is there anything wrong still?

**Comment by pinussilvestrus** [comment]
The commit message does not fit our guideline. A better name would be

```git
feat(select-entry-factory): add (optional) tooltip support for dropdown options 
```

**Comment by rajgoel** [comment]
Ah, ok. Upon creation of the PR a predefined template was shown to me and I simply adapted it (may be the template is outdated?).

**Comment by pinussilvestrus** [comment]
Yeah the template is broken in terms that the link to the guidelines is outdated (404). I'll fix that, thanks

**Comment by rajgoel** [comment]
Thanks for merging! 

Just out of curiosity and to learn: why is the commit message format important, do you run a tool that analyses or processes the commit messages?

**Comment by pinussilvestrus** [comment]
Yeah you're not far away from that. Given this list of reasons for using conventional commits: https://www.conventionalcommits.org/en/v1.0.0/#why-use-conventional-commits

The points of "communicating changes to stakeholder and team members" and "Making it easier for people to contribute to your projects, by allowing them to explore a more structured commit history" really fits for our case. We do not actively using automation on top of these but they help us to give a proper structure for bug fixes, new features and also misc changes.

These automation bits are potential things we could use on top of this communication aspect, but we're not using them currently, maybe only when creating or changelogs. Manually, but the commit structure helps a lot.

**Comment by rajgoel** [comment]
Cool. Thanks for the info!

**Pull request merged**
