### PR TITLE
Support Linked Camunda Form

### LINKED ISSUE #949: Camunda 8 Form Reference
The upcoming form deployment and linking feature will allow users to link to a deployed form through the properties panel. If the user chooses to embed, the existing _Form JSON Configuration_ field is shown.

image

If the user chooses to link, a new _Form ID_ field is shown.

image

### Tasks

- [ ] add select option for linked form
- [ ] add text field form ID

---

Product Hub Issue: https://github.com/camunda/product-hub/issues/419
Figma: https://www.figma.com/proto/ArESsfaYnKWs9XFJl0WgvW/Form-deployment?page-id=381%3A18143&type=design&node-id=408-17411&viewport=2287%2C1554%2C0.22&t=NTbiEanf5Udhzjts-1&scaling=scale-down&starting-point-node-id=408%3A17411

### PR DESCRIPTION
**Pull request by philippfromme**
* add _Camunda form (linked)_ option to _Type_ select
* add _Form ID_ input
* refactorings

image

---

Closes #949
Depends on https://github.com/camunda/camunda-bpmn-js-behaviors/pull/49

### CODE REVIEW

**Comment by nikku** [comment]
I [reached out to the Zeebe team](https://github.com/camunda/zeebe/issues/12874#issuecomment-1755544315) for clarification.

**Comment by barmac** [comment]
I'm moving this to draft until we clarify https://github.com/bpmn-io/bpmn-js-properties-panel/pull/978#issuecomment-1755905949

**Comment by barmac** [comment]
Back to ready I think: https://github.com/camunda/zeebe/issues/12874#issuecomment-1765966435

**Review by nikku — APPROVED** [review]
Works like a charm :heavy_check_mark:

**Pull request merged**
