### PR TITLE
Support completion condition for multi-instance

### LINKED ISSUE #530: Support completion condition for multi-instance
Zeebe may soon gain support for multi-instance completion condition, see [camunda-cloud/zeebe#5439](https://github.com/camunda-cloud/zeebe/issues/5439) and [camunda-cloud/zeebe#8321](https://github.com/camunda-cloud/zeebe/pull/8321).

Child of camunda/camunda-modeler#2641

### PR DESCRIPTION
**Pull request by Lzgabel**
Closes #530

### CODE REVIEW

**Comment by MaxTru** [comment]
Screenshot_20220103_104527

Screenshot_20220103_104552

Works like a charm! Thanks for this great contribution.

One thing:
You added a validation, which makes sense. However, we do not have validation in place at all at the moment. The reason for that is, that we will add an enhanced validation feature (ETA: April release). Because of that, could you please just remove the validation for now for consistency reasons? It will come back soon then with the April release (current plan). Thanks!

cc @andreasgeier

**Comment by Lzgabel** [comment]
>  Because of that, could you please just remove the validation for now for consistency reasons?

Done. 
Hi @andreasgeier, Please check this out. 🙇

**Review by MaxTru — APPROVED** [review]
Great job! Thanks for this contribution. Approved from Engineering side.

**Review by andreasgeier — APPROVED** [review]
Nice work, thank you! Approved.

**Comment by pinussilvestrus** [comment]
Seems like this one was targetting `next`, so we don't have these changes on `master` currently.

**Comment by MaxTru** [comment]
> Seems like this one was targetting `next`, so we don't have these changes on `master` currently.

@barmac please clarify which branch to use. We currently have `master` and `next` and it is not super clear what shall be used.

**Comment by barmac** [comment]
I'll merge `next` to `master` once again and then remove the branch.

**Comment by barmac** [comment]
Done.

**Pull request merged**
