### PR TITLE
feat(properties/HistoryCleanupProps): Add user document hint for hist…

### PR DESCRIPTION
**Pull request by prajwolbhandari1**
…ory time to live for bpmn

Related to https://github.com/camunda/camunda-modeler/issues/4062

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for your contribution! 

Two things:

* Could you update the PR to use tooltips over a description?
* Please use `https://docs.camunda.org/manual/latest/user-guide/process-engine/history/` as the documentation link

**Comment by prajwolbhandari1** [comment]
Yes, for sure. Thanks.

**Comment by nikku** [comment]
Thanks! Merged via https://github.com/bpmn-io/bpmn-js-properties-panel/commit/97ad3ae2f529b7e71a4da9df7ee90ed33c01a503.

**Comment by nikku** [comment]
@prajwolbhandari1 I extracted the tooltip into a pluggable provider via https://github.com/bpmn-io/bpmn-js-properties-panel/commit/cee1322c573bc36b504a9b242242a51eda696ee9.

Cf. https://github.com/camunda/camunda-bpmn-js/commit/9b403de0040caf0c9a272ab3f12c127a75c46b18 for integration into a standalone modeler.

**Pull request closed without merging**
