### PR TITLE
feat(template-util): display time for template versions

### LINKED ISSUE #694: Element Template Version with created metadata should include time
__Problem Description__

When multiple versions of a template are published at the same date, it is impossible to distinguish them and the "Update available" dropdown contains confusing information for the user as the new version date string is the same as the one of the currently used template:

image

__Solution Description__

Also include the time in the version information.

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #694

Displays the timestamp in the form _dd.MM.yyyy hh:mm_.

Bildschirmfoto 2022-06-07 um 15 07 21

### CODE REVIEW

**Comment by barmac** [comment]
Perhaps it makes sense to display ISO time or time with time zone?

**Comment by barmac** [comment]
> Working with dateTime could be anyway quite tricky. What about setting the timezone via [GitHub action](https://github.com/marketplace/actions/set-timezone)?

I'd rather set the timezone in Karma: https://blog.liprandi.net/2020/10/running-karma-in-specific-timezone.html

**Comment by pinussilvestrus** [comment]
I set the timezone via karma config as @barmac suggested (https://github.com/bpmn-io/bpmn-js-properties-panel/pull/698#issuecomment-1149808012).

> Perhaps it makes sense to display ISO time with time zone?

I'd not do it, as we don't do this [in the Web Modeler](https://github.com/camunda/web-modeler/blob/main/webapp/src/App/Pages/Project/utils.js#L13) (does not set timezones there).

**Comment by pinussilvestrus** [comment]
This is ready for review again.

**Comment by philippfromme** [comment]
Is it just me or is the overlay not always on top?

image

**Comment by pinussilvestrus** [comment]
You see correct 😆 I already created an issue for this (it's not related to this PR): https://github.com/bpmn-io/bpmn-js-properties-panel/issues/697

**Review by philippfromme — APPROVED** [review]
✅

**Pull request merged**
