### PR TITLE
fix(variableEvent): changing from camunda:VariableEvent to camunda:VariableEvents property #355

### LINKED ISSUE #355: The property camunda:variableEvent should be camunda:variableEvents
__Describe the Bug__

The camunda property field `camunda:variableEvent` for a conditional event is not recognized by Camunda because `camunda:variableEvents` is expected.

__Steps to Reproduce__

1. Create a conditional event
2. Modify the "Variable Event" property field
3. See that the resulting bpmn xml file ends up with the property `camunda:variableEvent` which is not recognized by Camunda

__Expected Behavior__ 

The expectation is something like this:
```
<bpmn:conditionalEventDefinition id="ConditionalEventDefinition_0wm7q4o" camunda:variableName="onlyOnUpdate" camunda:variableEvent="update">
    <bpmn:condition xsi:type="bpmn:tFormalExpression">${true}</bpmn:condition>
</bpmn:conditionalEventDefinition>
```

__Environment__

- Host (Browser/Node version), if applicable:  camunda-modeler
- OS: Manjaro Linux 20.1
- Library version: 0.35.0

### PR DESCRIPTION
**Pull request by prithviraj-maurya**
Closes #355

### CODE REVIEW

**Comment by prithviraj-maurya** [comment]
Please add hacktoberfest-accpted label if PR is successfully accepted

**Comment by pinussilvestrus** [comment]
Thanks for the PR. This also needs a fix inside [`camunda-bpmn-moddle`](https://github.com/camunda/camunda-bpmn-moddle/blob/master/resources/camunda.json#L1074).

**Review by pinussilvestrus — COMMENTED** [review]
Thanks for the PR. This also needs a fix inside [`camunda-bpmn-moddle`](https://github.com/camunda/camunda-bpmn-moddle/blob/master/resources/camunda.json#L1074). Without, we will run into unrecognized property errors.

**Comment by pinussilvestrus** [comment]
Hi @prithviraj-maurya to proceed with PR we need changes in the upstream [`camunda-bpmn-moddle`](https://github.com/camunda/camunda-bpmn-moddle/blob/master/resources/camunda.json#L1074) library. 

Can you maybe open a PR there as well, so we can manage to release those changes and integrate it here? We will then be able to finish this issue.

**Comment by prithviraj-maurya** [comment]
Ya sure will start working on it.

Thanks

**Comment by prithviraj-maurya** [comment]
Hi created PR for upstream library too please check 
https://github.com/camunda/camunda-bpmn-moddle/pull/58

**Comment by pinussilvestrus** [comment]
Nice!

**Comment by pinussilvestrus** [comment]
I merged it via 7a57cf4aedbf32a12bf31c7b949760362a3c912e. Thanks for your contribution!

**Comment by nikku** [comment]
Thank you @prithviraj-maurya. This is really a great contribution.

**Comment by prithviraj-maurya** [comment]
Happy to help. Learned a lot too. Looking forward to solving more bugs.

**Pull request closed without merging**
