### PR TITLE
#206

### PR DESCRIPTION
**Pull request by tomaszkrym**
Editing camunda:formKey and camunda:formData at the same time on user task - #206

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for your PR. Would you add a few test cases that verify

* formData / formKey can exist at the same time
* formData / formKey can independently be updated

**Comment by tomaszkrym** [comment]
@nikku 
Done - I've modified test data and added assertions.

The Travis build failed, but I feel that this is kind of a random failure, that is not caused by my changes (build of the branch is successful: https://travis-ci.org/Kodegenix/bpmn-js-properties-panel). I can't rerun build for the PR without making another commit.

**Comment by meyerdan** [comment]
Hey @tomaszkrym 

For what usecases do you need to specify both formData and formKey on the same usertask? I am aware of it being useful in at least the following two situations (but I am always interested to hear about your usecase):

* **Default values in a strart form**: I have a custom _start form_ specified with the form key but I want to use the from data for providing default values to some variables the start form is working with and I want to provide these default values in the BPMN process and not the 
* **Validation** I have a custom form but want to use form data for validating the input.

Which is yours?

**Comment by tomaszkrym** [comment]
@meyerdan 
The use case (described in #206 by @rjaros) is extending custom form with formData elements.

**Comment by philippfromme** [comment]
Closed via a241ef6730b1858d5f3ed7ac7d95a01d7e054527

**Pull request closed without merging**
