### PR TITLE
Template Input Output Groups

### LINKED ISSUE #345: Implement typeahead suggestion functionality for process variables in input parameter expressions
__Is your feature request related to a problem? Please describe__

Starting with https://github.com/bpmn-io/bpmn-js-properties-panel/issues/344 we offer the process variable mapping type for Camunda input parameters. We want to have a typeahead component for this mapping type to suggest possible process variables as mapping candidates.

The ongoing user research (cf. [Variable Management Prototype](https://rpa-prototypes.netlify.app/variable-management-new/?variant=A
)) shows that a suggestion of possible process variables as mapping candidate helps a lot to make fewer mistakes when mapping variables directly, in terms of typos and clarity, which process variable is available in the current context. The mechanism to detect those variables for the later suggestions is part of https://github.com/bpmn-io/bpmn-js-properties-panel/issues/342. 

__Describe the solution you'd like__

Something like the prototype is showing

image

While typing, the component should suggest variables found by the giving search string. When clicking (without changing) the component should show _all_ available variables.

Design requirements: https://zpl.io/2EM7eng

__Describe alternatives you've considered__

/

__Additional context__

Depends on https://github.com/bpmn-io/bpmn-js-properties-panel/issues/344.
Depends on #342 
Child of https://github.com/bpmn-io/internal-docs/issues/148
Related to [Variable Management Prototype](https://rpa-prototypes.netlify.app/variable-management-new/).

### LINKED ISSUE #358: Allow usage of improved input output parameter mapping component in element template view
__Is your feature request related to a problem? Please describe__

We want to support the user when working with process variables and mapping these to input / output parameters. As part of this, the user shall be able to perform the input/output mapping more easily.

This feature covers the integration of the new UI component (see https://github.com/bpmn-io/bpmn-js-properties-panel/issues/349) in the element template view (ie. the view in the properties panel after an element template was applied).

This affects the `camunda:inputParameter` and the `camunda:outputParameter` bindings in the `<elementTemplateConfig>.json`. 

__Describe the solution you'd like__

In the current state the user might configure an element template for `camunda:inputParameter` and `camunda:outputParameter` as following:
```
      {
        "label": "Some input var",
        "type": "String",
        "value": "${varA}",
        "binding": {
          "type": "camunda:inputParameter",
          "name": "someInputVar"
        }
      }
```
(Notice that in the following section when talking about `type` the third line of the above snippet is meant [and not the binding type]).
Hereby the `type` may be one of the following: `String`, `Text`, `Hidden`, `Dropdown` (`Boolean` doesnt make sense). This existing functionality **shall not be changed**.

In the target state, the new Input Output Parameter Mapping component (see #349) shall be rendered in the element template view (ie. the view in the properties panel after having applied an element template) **(1) if the binding is `camunda:inputParameter` or `camunda:outputParameter` and (2) if no type is specified in the `<...>.json`**. (Idea behind: the user UI component *defaults* to the default component).

If no type is specified in the `<...>.json` and the binding is one of the following: `property`, `camunda:property`, `camunda:in`, `camunda:in:businessKey`, `camunda:out`, `camunda:field`, **the rendered component shall default to `String`**.

If no type is specified in the `<...>.json` and the binding is `camunda:executionListener`, **the rendered component shall default to `Hidden`**.

If the new Input Output Paramter Mapping component is rendered, it shall be rendered in the Input Paramter, Output Parameter section (See [zeplin](https://app.zeplin.io/project/5e149dc7ef8eaa51b52af327/screen/5f3d4a24fe86422d21252e45))

If a `description` is provided, it shall be rendered as specified in zeplin.

__Describe alternatives you've considered__

n/a

__Additional context__

See [zeplin](https://app.zeplin.io/project/5e149dc7ef8eaa51b52af327/screen/5f3d4a24fe86422d21252e45)

### PR DESCRIPTION
**Pull request by pinussilvestrus**
__Which issue does this PR address?__

Closes #358 

__Acceptance Criteria__

* [ ] Corresponds to the concept #345 
* [ ] Corresponds to the design https://zpl.io/2GLpDkE

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

--------------------------
Depends on Changes of #360 
Depends on Changes of #364 
Depends on Changes of #367

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
**Tasks to be done**
* [ ] handle descriptions for input / output parameter
* [ ] input parameter shown label --> (1) property.label, (2) property.binding.name
* [ ] output parameter shown label --> (1) property.label
* [ ] remove default setting of input / output parameter on apply
* [ ] write missing tests
* [ ] rebase to other changes (cf. PR description - bottom)

**Comment by pinussilvestrus** [comment]
I rebased the changes on top of #367, so it is basically read for review. Note that only the lasts two commits are related to this PR.

**Comment by pinussilvestrus** [comment]
Artifacts for Design review @andreasgeier 

Linux
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/358-template-input-output/camunda-modeler-358-template-input-output-linux-x64.tar.gz

Mac
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/358-template-input-output/camunda-modeler-358-template-input-output-mac.dmg
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/358-template-input-output/camunda-modeler-358-template-input-output-mac.zip

**Comment by andreasgeier** [comment]
Currently, there is no behavior in place that blocks long variable descriptions from consuming the whole panel. Can we implement the same expand/collapse (More ... Less ...) behavior as we do for the template description?

Screen Shot 2020-09-24 at 11 46 43

**Comment by pinussilvestrus** [comment]
This should be doable. The question is whether we want this? 

I'd argue to not spend another time on this since I don't think descriptions for variables will be that long. Descriptions can be like this in nearly any entry of the properties panel and they won't be cropped. 

I'm not sure whether we want to implement it just for this case or rather have something more generic. Anyway, maybe not cropping the descriptions will hold users away from creating such big descriptions.

What do you think @barmac @philippfromme @MaxTru @volkergersabeck?

**Comment by MaxTru** [comment]
> This should be doable.
> 
> I'm not sure whether we want to implement it just for this case or rather have something more generic.
> 
> What do you think @barmac @philippfromme @MaxTru @volkergersabeck?

Thanks for raising this.

Let's go for it. In addition I create a issue so to harmonize the description cropping behavior.

**Comment by pinussilvestrus** [comment]
@andreasgeier I adjusted this behavior 👍 

Kapture 2020-09-24 at 13 02 51

We decided to also have this in other places, like the custom field descriptions. We will open an issue for that.

**Review by andreasgeier — APPROVED** [review]
UI is okay

**Review by philippfromme — CHANGES_REQUESTED** [review]
As discussed with @pinussilvestrus we do not want to introduce a new type (`InputOutputCollapsibleItem`) but rather have a default entry when there is no type. The user should not be able to use the `InputOutputCollapsibleItem` type explicitly. Instead, the validation should accept a missing type and when creating the entry there should be a default.

**Comment by pinussilvestrus** [comment]
I updated it accordingly
* allow empty types in validation
* render default component on empty type (custom props, input/output collapsible)

**Review by philippfromme — APPROVED** [review]
👍

**Review by barmac — APPROVED** [review]

**Pull request merged**
