### PR TITLE
chore(CHANGELOG): update to v1.17.0

### PR DESCRIPTION
**Pull request by philippfromme**
## Changes

https://github.com/bpmn-io/bpmn-js-properties-panel/compare/v1.6.1...master

* `FEAT`: show conditions group if source is inclusive gateway ([#756](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/756))
* `FEAT`: support element template properties without default value ([#763](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/763))
* `FEAT`: support deprecated element templates ([#766](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/766))
* `FIX`: support `zeebe:property` binding for creation of elements from element templates ([#762](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/762))
* `FIX`: support conditional properties for creation of elements from element templates ([#762](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/762))
* `CHORE`: remove default values from _Variable assignment value_ of _Input_ and _Output_ ([#757](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/757))
* `DEPS`: update to `@bpmn-io/properties-panel@0.21.0`

### CODE REVIEW

**Comment by nikku** [comment]
Proposal: Let's incorporate https://github.com/bpmn-io/bpmn-js-properties-panel/pull/766.

**Comment by nikku** [comment]
Let's add https://github.com/bpmn-io/bpmn-js-properties-panel/commit/f5eaf3e443384229ec8a32572888cb64cb3c47b1.

**Comment by philippfromme** [comment]
Okay, @nikku I will add these 👍🏻

**Comment by nikku** [comment]
Let's incorporate https://github.com/bpmn-io/bpmn-js-properties-panel/commit/232047326bf87b37bd76cacaf724bafa3b1094d9.

**Comment by philippfromme** [comment]
@nikku Added.

**Review by barmac — APPROVED** [review]
🏎️

**Pull request merged**
