### PR TITLE
Use collapsible for input output mapping

### LINKED ISSUE #350: Improved Input/Output mapping component is integrated in existing Input/Output tab
__Is your feature request related to a problem? Please describe__

We want to support the user when working with process variables. As part of this, the user shall be able to perform the input/output mapping more easily.

This feature covers the integration of the new UI component which replaces the existing input/output mapping (which is implemented as list) into the `Input/Output tab`.

__Describe the solution you'd like__
The current `Input/Output tab` uses this component:
Screenshot_20200818_120611

The new component (see #349) shall be used instead. 

__Additional context__

Child of https://github.com/bpmn-io/internal-docs/issues/148
Depends on #349 
Depends on #344

### PR DESCRIPTION
**Pull request by barmac**
__Which issue does this PR address?__

Closes #350

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Review by pinussilvestrus — COMMENTED** [review]
Some of the tests are failing on CI. Besides that, everything looks fine to me 👏

**Comment by barmac** [comment]
@andreasgeier
Links for design review:

- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/350-use-collapsible-for-input-output-mapping/camunda-modeler-350-use-collapsible-for-input-output-mapping-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/350-use-collapsible-for-input-output-mapping/camunda-modeler-350-use-collapsible-for-input-output-mapping-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/350-use-collapsible-for-input-output-mapping/camunda-modeler-350-use-collapsible-for-input-output-mapping-mac.zip

For some reason I can't assign you to the review, though.

**Comment by pinussilvestrus** [comment]
He was not part of the modeling-design team. I just invited him.

**Review by andreasgeier — APPROVED** [review]
Greenlight for the UI*

*Note: given the technical limitations of the property panel, it was not possible to consider all design details like spacing, alignment, etc. However, this is accepted for the time being.

**Review by pinussilvestrus — APPROVED** [review]
As I said in [this comment](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/367#pullrequestreview-494244729), the changes look good to me. I'd let open for @philippfromme to give his final opinion.

**Review by philippfromme — APPROVED** [review]
Good job! 👏

**Pull request merged**
