### PR TITLE
Prepare v5.6.0

### PR DESCRIPTION
**Pull request by nikku**
Let's cut this release to integrate the changes downstream!

### CODE REVIEW

**Comment by smbea** [comment]
Let's just resolve conflicts and we can go ahead

**Comment by nikku** [comment]
Doing it!

**Comment by nikku** [comment]
Updated.

**Review by smbea — APPROVED** [review]

**Comment by barmac** [comment]
Shall we hold this till https://github.com/bpmn-io/bpmn-js-element-templates/pull/25#issuecomment-1768763108?

**Comment by barmac** [comment]
🔴 If we update `camunda-bpmn-js-behaviors`, the `zeebe:subscription` will be broken due to the same reason as in `bpmn-js-element-templates`. We should add the property in one go instead of multi-command shenanigans: https://github.com/bpmn-io/bpmn-js-properties-panel/blob/main/src/provider/zeebe/properties/MessageProps.js#L138

**Review by barmac — CHANGES_REQUESTED** [review]
Let's integrate behaviors correctly (I will do that).

**Review by barmac — APPROVED** [review]

**Comment by barmac** [comment]
Done via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/991/commits/a06e55c851984af5c28872fb323d7dc775dea6c0

This shows how `multicommand` command breaks the command atomicity :/

**Pull request merged**
