### PR TITLE
Add `Version tag` field

### PR DESCRIPTION
**Pull request by philippfromme**
### Proposed Changes

* adds _Version tag_ field to processes

image

* adds _Version tag_ field to resources linked through _version tag_ option

image

* adjusts the _Binding type_ tooltip

image

Requires https://github.com/camunda/zeebe-bpmn-moddle/pull/65
Requires https://github.com/camunda/camunda-bpmn-js-behaviors/pull/80

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [x] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by philippfromme** [comment]
This pull request depends on https://github.com/camunda/camunda-bpmn-js-behaviors/pull/80 being integrated first.

**Comment by philippfromme** [comment]
Ready for review.

**Comment by nikku** [comment]
Quick clarficiation: Is `versionTag` provided via linking static only? I was under the impression we'd support dynamically computed tags:

image

**Review by nikku — COMMENTED** [review]
Good work! Ready to be merged, if static version tag is what we implemented (https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1063#issuecomment-2309954696), pending confirmation.

**Review by nikku — APPROVED** [review]
Verified we [only support static bindings for now](https://camunda.slack.com/archives/C075V1L1TAN/p1724671736051319?thread_ts=1724670812.005579&cid=C075V1L1TAN) :heavy_check_mark:

**Comment by nikku** [comment]
@philippfromme I'll go ahead and release this :handshake:

**Comment by nikku** [comment]
Released as https://github.com/bpmn-io/bpmn-js-properties-panel/releases/tag/v5.23.0.

**Pull request merged**
