### PR TITLE
fix(elementTemplates): reorder unlink / remove actions in dropdown

### LINKED ISSUE #498: The Unlink button is easy to overlook when template is unknown
__Describe the Bug__

During the 9th November weekly, it was expressed that the unlink button is hard to spot for unknown template dropdown.

image

__Steps to Reproduce__

1. Select a shape with an unknown template
2. Click the dropdown
3. now this happens

__Expected Behavior__

It should be as easy to spot as the remove button.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

### PR DESCRIPTION
**Pull request by MaxTru**
Screenshot_20220117_090812
Screenshot_20220117_090821

closes #498

### CODE REVIEW

**Comment by MaxTru** [comment]
Corrected
Screenshot_20220117_092320
Screenshot_20220117_092336

**Comment by andreasgeier** [comment]
@MaxTru pls provide an artifact to test

**Comment by MaxTru** [comment]
> @MaxTru pls provide an artifact to test

Sure, please start using this command:
```
npx @bpmn-io/sr "bpmn-io/bpmn-js-properties-panel#498-reorder-template-actions" "-c=npm run start:templates"   
```

Let me know, if you need help.

**Review by andreasgeier — APPROVED** [review]
✅ LGTM

**Pull request merged**
