### PR TITLE
fix(cloud): remove timeCycle for interrupting timer start event

### PR DESCRIPTION
**Pull request by barmac**
image

This removes time cycle if start event is interrupting. Also, as part of a clean up, the code is simplified together with duration label (it used to be "Timer duration"):

image

Related to https://github.com/camunda/camunda-modeler/issues/3181

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
+1 for the label update. It also follows other labels, e.g. we do not say "Timer type" or "Timer value"

image

I remember we tried these shorter labels when we introduced the new properties panel. I thought something would be mentioned in [our design docs](https://github.com/camunda/modeler-design/blob/main/docs/technical-writing.md), but apparently, not.

**Comment by barmac** [comment]
The CI failed because we apparently don't use `#bio-properties-panel-timerEventDefinitionValue` id for FEEL expressions.

**Comment by nikku** [comment]
+1 for simplification / reducing redundancy in labels where context is clear.

**Comment by nikku** [comment]
Exceptions exist (i.e. process ID vs. participant ID).

**Review by pinussilvestrus — APPROVED** [review]
LGTM!

**Pull request merged**
