### PR TITLE
fix(cloud-templates): keep exisiting configuration after apply

### PR DESCRIPTION
**Pull request by marstamm**
Recording 2022-04-12 at 12 02 33

related to #638

### CODE REVIEW

**Comment by nikku** [comment]
My proposal is that we start to test element template logic against the new APIs (`ElementTemplate#applyTemplate`) rather than internally. That will help us long term.

**Comment by marstamm** [comment]
We are already testing against this API, just with some utility around it to ensure the templates are added beforehand:

https://github.com/bpmn-io/bpmn-js-properties-panel/blob/522155a8b3f849e36814805c0f78a882e15a0821/test/spec/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js#L2273-L2284

**Comment by nikku** [comment]
Sorry, my bad. What I meant is "move the test to that place" (or consider not to do it).

**Comment by marstamm** [comment]
I like having it as a separate file from `ElementTemplates.spec`, as we are testing the behavior of the `ChangeElementTemplateHandler` and is easier to find in the IDE this way.

But this is just a slight preference, no strong feelings either way

**Comment by nikku** [comment]
> https://github.com/bpmn-io/bpmn-js-properties-panel/pull/661#issuecomment-1094700091

Great, in this case let us keep it.

I'll just make sure we have some basic coverage in the element template spec, too.

**Comment by marstamm** [comment]
@nikku, how do we want to continue with this PR? From my side, the implementation for keeping configuration C8 is ready for review. Do you want to add the test cases to this PR or is this a separate issue/PR?

**Comment by marstamm** [comment]
To be confirmed: this PR solved https://camunda.slack.com/archives/C02JLRNQQ05/p1649846975972899 

(double taskDefinitions after applying template to configured service task). I will add an explicit test case for this

**Comment by marstamm** [comment]
Added integration tests. This is ready for review now.

**Comment by nikku** [comment]
My appologies for not looking into this earlier. I have this PR on my list for tomorrow :pray:

**Review by nikku — APPROVED** [review]
Works as it should :+1: 

Found one unrelated visual glitch: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/675.

**Pull request merged**
