### PR TITLE
House keeping

### PR DESCRIPTION
**Pull request by nikku**
Usual dependency updates, and dropping unused + deprecated `@testinglibrary/preact-hooks` dependency.

### CODE REVIEW

**Comment by barmac** [comment]
This fails badly in the CI. Looks like `preact` is missing from the legacy `@bpmn-io/properties-panel`.

**Comment by barmac** [comment]
It is installed though: https://unpkg.com/browse/@bpmn-io/properties-panel@3.10.0/preact/

**Comment by nikku** [comment]
Reverted the `mjs` rename that caused this - https://github.com/bpmn-io/properties-panel/pull/305.

**Comment by barmac** [comment]
This will make sure that we know immediately if the problem comes from integration deps or not: https://github.com/bpmn-io/bpmn-js-properties-panel/pull/987

**Comment by nikku** [comment]
Should be fixed via upstream `v3.10.1` release.

**Review by barmac — APPROVED** [review]

**Pull request merged**
