### PR TITLE
Support Camunda 8.3 Signal Event Properties

### PR DESCRIPTION
**Pull request by philippfromme**
* add _Inputs_ group for signal intermediate throw and end events
* change signal _Name_ entry to optional FEEL entry

image

---

Closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/909

### CODE REVIEW

**Comment by smbea** [comment]
is this ready for review? no reviewers were assigned

**Review by marstamm — COMMENTED** [review]
Great stuff! I only found one unexpected behavior: when replacing a signal catch with a throw event, the signal reference gets lost
Recording 2023-05-08 at 10 53 38 (1)

**Comment by philippfromme** [comment]
> when replacing a signal catch with a throw event, the signal reference gets lost

Ok, let me have a look at that. 👀

**Comment by philippfromme** [comment]
@marstamm The issue with the signal reference is unrelated to this pull request. I created an issue: https://github.com/bpmn-io/bpmn-js/issues/1906. We can fix this separately.

**Review by marstamm — APPROVED** [review]
Then this is good to go from my side 🚀

**Pull request merged**
