### PR TITLE
feat(DMN): add hints on the returned Java types

### PR DESCRIPTION
**Pull request by falko**

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for your PR. 

Just based on the code you submitted (without any explaination) it is not quite clear what you would you like to achieve. Could you elaborate why this is an improvement (from the user perspective)?

**Comment by falko** [comment]
Sorry for my brevity while opening this live during a customer workshop.

In consulting, we frequently experience that customers do not understand the result mapping and what they can expect from the different settings. In our developer trainings, we explain that with the resulting Java types. So the next logical step was to put that type hint also into the labels shown in the property panel. That way users can decide easier and don't have to search the docs or write unit tests in order to figure it out.

**Comment by falko** [comment]
To give even more context:
DMN Decision Tables have different result structures, depending on the Hit Policy. By selecting a mapping that matches the result structure of their model, users can simplify the work with the result later in the process, e.g. in expressions.

**Comment by nikku** [comment]
As an alternative to your solution we could simply link the docs, too. Which solution would you prefer?

**Comment by falko** [comment]
Both.

**Comment by falko** [comment]
I guess, this would be the right link to put: https://docs.camunda.org/manual/latest/user-guide/process-engine/decisions/bpmn-cmmn/#predefined-mapping-of-the-decision-result

Nevertheless, we could save people some time by directly putting the hints in the labels, which are not exactly self-explanatory.

**Comment by falko** [comment]
Should this already be available in 3.0.0-nightly builds? I didn't see it there.

**Comment by nikku** [comment]
It is in there, however with a display bug:

image

**Comment by falko** [comment]
> It is in there, however with a display bug:
> 
> image

Any idea how to fix that display bug? Encoding? HTML entities?

**Comment by nikku** [comment]
We do not properly sanitize element labels we build the UI from: https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/factory/SelectEntryFactory.js#L51

This means that entities such as `<` have interesting effects on the UI.

**Comment by nikku** [comment]
I've created https://github.com/bpmn-io/bpmn-js-properties-panel/issues/296 to track the bug.

**Comment by falko** [comment]
Is there anything that I can do as a workaround until #296 is fixed?

**Comment by nikku** [comment]
Unfortunately not. We schedule this as a bug in our next milestone.

**Pull request merged**
