### PR TITLE
feat(camunda): add Camunda Forms properties

### LINKED ISSUE #480: Allow Configuring Camunda Forms
Backports https://github.com/bpmn-io/bpmn-properties-panel/issues/96.

### PR DESCRIPTION
**Pull request by philippfromme**
electron_nOGFeu9g5Z

---

Closes #480
Related to https://github.com/camunda/camunda-modeler/issues/2295

### CODE REVIEW

**Comment by nikku** [comment]
@philippfromme Is this ready for review?

**Comment by philippfromme** [comment]
> @philippfromme Is this ready for review?

Oops. Yes, ready!

**Comment by nikku** [comment]
How to try this one out in action? Oneliners only, plz. :wink:

**Comment by philippfromme** [comment]
> How to try this one out in action? Oneliners only, plz. 😉

No one-liners, unfortunately. Locally linking the project and trying it out in camunda-bpmn-js is the way to go.

**Review by nikku — APPROVED** [review]
Implementation clean, works as expected :clap:

**Pull request merged**
