### PR TITLE
Only variable complete fields backed by IO mappings

### PR DESCRIPTION
**Pull request by nikku**
This prevents us from providing bogus suggestions.

Related to https://github.com/camunda/camunda-modeler/issues/3525

----

capture 8TR03a_optimized

### CODE REVIEW

**Comment by nikku** [comment]
@marstamm Do you have a specific way in mind how I can test this? I'd otherwise just leave it as manually tested for the time being.

**Comment by marstamm** [comment]
Looking into it right now

**Comment by marstamm** [comment]
I found no easy way to test this without stubing/dynamically mocking modules, for which we currently don't have the infrastructure.

I made some changes so that the Editor still uses the TooltipContainer provided. Other than that, I'm okay with merging it as-is

**Comment by nikku** [comment]
Great. Thanks for having a look.

**Comment by nikku** [comment]
I'll go ahead and release this.

**Pull request merged**
