### PR TITLE
fix: add missing translations in header and tab labels

### LINKED ISSUE #1044: Panel headers and Zeebe's tab labels translations are missing
### Describe the Bug

In current state, exists [translation](https://github.com/bpmn-io/bpmn-js-examples/tree/main/i18n ) functionality, which works only on some of the tab's labels (#1014).
In header's case, no header can be translated.  

### Steps to Reproduce

1.) Create custom translate function, which translates any word into some symbol:
```js
export default {
  translate: [
    'value',
    function customTranslate(template, replacements) {
      return '✔';
    },
  ],
};
```

2.) Apply it to bpmn modeler
```js
import {
  BpmnPropertiesPanelModule,
  BpmnPropertiesProviderModule,
  ZeebePropertiesProviderModule,
} from 'bpmn-js-properties-panel';

import testTranslation from '@/some/path/toFile';
...
const options = {
  propertiesPanel: { parent: '#js-properties-panel' },
  additionalModules: [
    BpmnPropertiesPanelModule,
    BpmnPropertiesProviderModule,
    ZeebePropertiesProviderModule,

    testTranslation,
  ],
};

const bpmnViewer = new BpmnModeler(options);
```

3.) Check result:
image

We can see that headers and some tabs are not translated.
(It seems that all Zeebe's tabs are not translated)

### Expected Behavior

All headers and tab's labels should be translated

### Environment

- Host: Node v.20.11.1
- OS: Windows 11
- Library version: 5.14.0

### PR DESCRIPTION
**Pull request by Rastuharem**
Closes #1044

### CODE REVIEW

**Review by barmac — APPROVED** [review]
Makes sense. Thank you!

**Review by barmac — CHANGES_REQUESTED** [review]
I run the CI tests on this and it looks that the tests need to be adjusted yet.

Once you fix this, please adjust the commit to contain "Closes #issue_number" in the body.

**Comment by Rastuharem** [comment]
Thanks for quick responce @barmac!
I ammended first commit to change 'feat:' prefix to 'fix:'. Second commit should fix unpassed tests.

**Comment by barmac** [comment]
Thanks! I will run the CI on this, and if any problems remain, I will fix that before merging your contribution.

**Pull request merged**
