### PR TITLE
Integrate properties-panel 3.8.0

### PR DESCRIPTION
**Pull request by nikku**
https://github.com/bpmn-io/properties-panel/compare/v3.7.1...v3.8.0

### CODE REVIEW

**Comment by nikku** [comment]
This seems to fail two tests, probably due to https://github.com/bpmn-io/properties-panel/commit/381c51782e80a0404b9d310a7b6e48efe8b4216e? I'll investigate.

**Comment by nikku** [comment]
Proposing to make our existing tests more robust, cf. https://github.com/bpmn-io/bpmn-js-properties-panel/pull/979/commits/86221d5d07769e91f4ce8f84d116055b4327c857.

**Review by barmac — APPROVED** [review]

**Comment by barmac** [comment]
Cursor can be still funny on Mac though:

https://github.com/bpmn-io/bpmn-js-properties-panel/assets/28307541/283556fa-ba0b-4eaf-8c43-587efbf3ff87

**Comment by nikku** [comment]
@barmac Same I found on Firefox (Linux). We have a fix in place though.

**Pull request merged**
